---
title: "Hook arguments"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hook-arguments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Arguments are specified as described in the [pre-commit.com
documentation](https://pre-commit.com/#passing-arguments-to-hooks), i.e. the
arguments for the `style-files` hook can be set like this:

```{r, echo = FALSE, output = "asis", comment = ""}
library(magrittr)
config <- yaml::read_yaml(system.file("pre-commit-config.yaml", package = "precommit", mustWork = TRUE))
rev <- purrr::imap(config$repos, function(x, y) {
  if (x$repo == "https://github.com/lorenzwalthert/precommit") {
    return(x$rev)
  }
}) %>%
  purrr::compact() %>%
  unlist()
cat(glue::glue("
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v{rev}
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
"))
```

The following hooks take arguments:

* `style-files`: Argument `style_pkg` and `style_fun` if you want to use another
  style guide than the default. Defaults: `styler` for `style_pkg` and 
  `tidyverse_style` for `style_fun`.
  ```
  id: style-files
  args: [--style_pkg=styler, --style_fun=tidyverse_style]
  ```
* `spell-check`: Argument `ignore_files` takes a regular expression matched with
  `base::grep()` to ignore further files from the hook. Argument `lang` is
  passed to `spelling::spell_check_files()`.
  ```
  id: spell-check
  args: [--ignore_files=<ignored_files>, --lang=<language>]
  ```

* `lintr`: Argument `warning_only` changes the behavior of the pre-commit to
  be non-blocking. You should set this with the field `verbose: true`.

  ```
  id: lintr
  args: [--warn_only]
  verbose: true
  ```
  When configured this way, lintr prints lint errors as they appear. Other
  arguments are not supported. Instead, `lintr` config should be specified in a
  `.lintr` config file in Debian Control Field Format as specified in the
  [`.lintr`
  documentation](https://github.com/jimhester/lintr#project-configuration).

* `deps-in-desc`: Flag `allow_private_imports` lets the user specify that
  private imports into the package namespace are tolarable, e.g. 
  `somepkg:::x()`. Flag not set by default, i.e. the hook will fail if 
  such a call is found.
  ```
  id: deps-in-desc
  args: [--allow_private_imports]
  ```
