# NB: DO NOT EDIT. Auto-generated by .dev/gen_roxygen_tests.R.

test_that("analogous to test-roxygen-examples-complete: 26", {
  expect_warning(test_collection("roxygen-examples-complete", "^26-", transformer = style_text), NA)
})
