# NB: DO NOT EDIT. Auto-generated by .dev/gen_roxygen_tests.R.

test_that("analogous to test-roxygen-examples-complete: 12", {
  expect_warning(test_collection("roxygen-examples-complete", "^12-", transformer = style_text), NA)
})
