# NB: DO NOT EDIT. Auto-generated by tests/dev/generate_roxygen_tests.R.

test_that("analogous to test-roxygen-examples-complete: 02", {
  expect_warning(test_collection("roxygen-examples-complete", "^02-", transformer = style_text), NA)
})
