# NB: DO NOT EDIT. Auto-generated by ./tests/dev/generate_roxygen_tests.R.

test_that("analogous to test-roxygen-examples-complete: 28", {
  expect_warning(test_collection("roxygen-examples-complete", "^28-", transformer = style_text), NA)
})
