# NB: DO NOT EDIT. Auto-generated by ./tests/dev/generate_roxygen_tests.R.

test_that("analogous to test-roxygen-examples-complete: 15", {
  expect_no_warning(test_collection("roxygen-examples-complete", "^15-", transformer = style_text, scope = "spaces"))
})
