#!/usr/bin/Rscript
# execute from package TLD: ./.dev/gen_roxygen_tests.R
all_examples <- list.files("tests/testthat/roxygen-examples-complete", full.names = TRUE)
unique_tests <- unique(sub("-.*", "", basename(all_examples)))

for (test in unique_tests) {
  out_file <- file.path("tests", "testthat", paste0("test-roxygen-examples-complete-", test, ".R"))
  extras <- if (test == "15") ', scope = "spaces"' else ""
  writeLines(con = out_file, c(
    "# NB: DO NOT EDIT. Auto-generated by .dev/gen_roxygen_tests.R.",
    "",
    sprintf('test_that("analogous to test-roxygen-examples-complete: %s", {', test),
    sprintf('  expect_warning(test_collection("roxygen-examples-complete", "^%s-", transformer = style_text%s), NA)', test, extras),
    "})",
    NULL
  ))
}
