#!/usr/bin/Rscript
# execute from package TLD: ./.dev/gen_roxygen_tests.R
roxygen_stub <- "roxygen-examples-complete"
all_examples <- list.files(file.path("tests", "testthat", roxygen_stub))
unique_tests <- unique(sub("-.*", "", all_examples))

# tests using 'scope = "spaces"' in test_collection()
tests_scope_spaces <- "15"

warning_map <- c(`23` = '"issues/1242"')

for (test in unique_tests) {
  out_file <- file.path("tests", "testthat", paste0("test-", roxygen_stub, "-", test, ".R"))
  extras <- if (test %in% tests_scope_spaces) ', scope = "spaces"' else ""
  writeLines(con = out_file, c(
    "# NB: DO NOT EDIT. Auto-generated by .dev/gen_roxygen_tests.R.",
    "",
    sprintf('test_that("analogous to test-%s: %s", {', roxygen_stub, test),
    sprintf(
      '  expect_warning(test_collection("%s", "^%s-", transformer = style_text%s), %s)',
      roxygen_stub, test, extras, warning_map[test]
    ),
    "})",
    NULL
  ))
}
