\documentclass{article}
\usepackage{amsmath}
\begin{document}

When the option OutDec is not \texttt{.}, put numbers in \texttt{\textbackslash{}text}. See \#348.

<<>>=
options(OutDec = ",")
@

This is the first test. abc \Sexpr{0.6} def

another test $a = \Sexpr{0.6}$.

and the last one $a = \Sexpr{'0.6'}$.

<<>>=
options(OutDec = ".")
@

This is the first test. abc \Sexpr{0.6} def

another test $a = \Sexpr{0.6}$.

and the last one $a = \Sexpr{'0.6'}$.

\end{document}
